reference:
  genome_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.fna.gz
  genome_name: TAIR10
  genome_alias: "config/alias.csv"
  annotation_url: https://www.arabidopsis.org/download_files/Genes/Araport11_genome_release/archived/Araport11_GTF_genes_transposons.Mar202021.gtf.gz
  annotation_name: Araport11
  annotation_filter:
    - miRNA
    - transposable_element
    - transposon_fragment

STAR:
  read_length: 100
  options: "--genomeSAindexNbases 12 --quantMode TranscriptomeSAM"

feature_counts:
  options: "-Q 5 -s 2 -B"

samtools_view:
  flags: "-f 2 -F 4 -q 5"

deseq2:
  control: col0

dexseq:
  options: "-s reverse"

stringtie:
  options: "--rf"
