# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /opt/recipe, last modified Fri Mar 26 14:36:27 2021
# ------------------------------------------------

package:
  name: danpos
  version: 2.2.2
source:
  md5: ea2d16c7d07009d6fb7b397ea857575b
  url: http://lilab.research.bcm.edu/dldcc-web/lilab/kaifuc/danpos/release/danpos-2.2.2.tgz
build:
  noarch: generic
  number: '2'
  string: hdfd78af_2
requirements:
  build: []
  run:
    - icu
    - numpy
    - python <3
    - r-base
    - rpy2
    - samtools <1
test:
  commands:
    - danpos.py -h
about:
  home: https://sites.google.com/site/danposdoc/
  license: Unknown
  summary: A toolkit for Dynamic Analysis of Nucleosome and Protein Occupancy by Sequencing,
    version 2
extra:
  copy_test_source_files: true
  final: true
